### ISSUE TITLE
Osa 1 - "Loogiset operaatiot": kirjoitusvirhe

### ISSUE THREAD

**Issue by rva194800** [rage/ohjelmointi-20#110]
Virke: "Loogista operaatiota **ei käytetään** totuusarvon muuntamiseen truesta falseksi tai falsesta trueksi."
-> pitäisikö olla "**ei käytetä"**? 
-> vaiko "_käytetään_?"

**Comment by Silviis** [comment]
Virkkeellä tarkoitetaan nimenomaan loogista operaatiota 'ei'. Oikeaoppisemmin virke siis olisi: "Loogista operaatiota 'ei', käytetään totuusarvon muuntamiseen truesta falseksi tai falsesta trueksi."

**Comment by rva194800** [comment]
Kiitos! Kyllähän se nyt on ihan järkeenkäypä, kun sen lukee huolellisesti. Kiitos selvennyksestä! :-)
