### ISSUE TITLE
Error: Request failed with status code 500

### ISSUE THREAD

**Issue by ArtoR2** [rage/ohjelmointi-20#19]
Edistymisen hakeminen kaatui seuraavaan virheeseen: Error: Request failed with status code 500

Ilmaantui osion 2 tehtävän 2 jälkeen.

**Comment by nygrenh** [comment]
Moi,

Valitettavasti en saa ongelmaa toistettua omilla tunnuksillani. Voisitko ottaa osoitteeseen mooc@cs.helsinki.fi yhteyttä niin selivitetään siellä tarkemmin mikä on ongelmana?

**Comment by ArtoR2** [comment]
Hei,

Tuo edistymistä koskeva asia näkyy ratkenneen itsestään, eli nyt tekemiset
taas päivittyvät online.

Osion 2 tehtävän 8 kanssa on enemmän ongelmia:

- tehtävän ensimmäisestä testivastauksesta pystyi päättelemään, että ohelma
piti laatia siten, että lukuja voi syöttää vain viisi kertaa. Tätä ei
sanottu tehtävän toimeksiannossa.
- kun tehtävän sitten muokkasi siihen muotoon, että vain viisi kertaa voi
lukuja syöttää, sen testit antavat ristiriitaiset tulokset tekemäni
ohjelman Netbeansin ohjelman tulostusten kanssa?! Sain itse kyllä aivan
oikeat tulokset. Testit ja omat tulokseni liitteenä.

Tosi upean MOOCin olette joka tapauksessa laatineet, kivasti pääsee
asioihin sisälle! Kaikessa on toki aina pientä hiomista.

Terveisin,

Arto Talmo
Kirkkokatu 27 B 3
SF-10300 KARJAA
FINLAND
+358 40 177 5750


to 9. tammik. 2020 klo 16.21 Henrik Nygren (notifications@github.com)
kirjoitti:

**Comment by ArtoR2** [comment]
PERUUTAN EDELLISEN VIESTINI, OLIN TEHNYT TEHTÄVÄN 7 OHJELMAN TEHTÄVÄN 8
POHJAAN!!

Oma moka siis, anteeksi vaivannäöstä.

Terveisin,

Arto Talmo
Kirkkokatu 27 B 3
SF-10300 KARJAA
FINLAND
+358 40 177 5750


to 9. tammik. 2020 klo 17.13 Arto Talmo (arto.talmo@gmail.com) kirjoitti:
