### ISSUE TITLE
"Checkstyle runner error:" virhe lähettäessä koodia testattavaksi

### ISSUE THREAD

**Issue by LeeviHalme** [rage/ohjelmointi-20#22]
En tiedä onko tämä oikea paikka näille, mutta aina välillä lähettäessä koodia TestMyCode:lle tulee virheilmoitus `Checkstyle runner error:`. Tämä on alkanut vasta kolmannessa osassa, eli aiempien osien tehtävissä ei ole tällaista tullut vastaan.

Tämä korjaantuu odottamalla noin 30 sekuntia ja painamalla "submit" uudelleen. En tosin usko, että tämä on ns. ominaisuus 😄

**Comment by hennahautakoski** [comment]
Alkoi täälläkin tänään ja toisen osan tehtäviä tekemässä :)

**Comment by nygrenh** [comment]
Kiitos ilmoituksesta. Ongelma on nyt korjattu ja ei-toimineet palautukset on nyt ajettu uudestaan niin oikein tehdyistä tehtävistä on tullut pisteet kaikille.
