### ISSUE TITLE
Osio 3: Yksinkertaisia piiloviestejä, kirjoitusvirhe

### ISSUE THREAD

**Issue by Kriisi** [rage/ohjelmointi-20#25]
"Yllä olevissa tehtävissä on oikeastaan toteutettu hyvin yksinkertaisten piiloviestien purkumenetelmä. Eräs tällaisten piiloviestien variantti koostuu kunkin rivin ensimmäisestä merkistä. Esimerkiksi seuraavaan (hieman sekavaan) tekstiin on piilotettu viesti "ohjelmointi"."

Oikeasti rivien ensimmäiset merkit muodostavat merkkijonon "OHJELMA"

**Comment by ConcernedHobbit** [comment]
Korjattu (c424dd9). Kiitos ilmoituksesta!
