### ISSUE TITLE
Tehtävä 06_13  Maven Plugin

### ISSUE THREAD

**Issue by koenol** [rage/ohjelmointi-20#42]
"Testivetoinen ohjelmointikehitys" esimerkkiä seuratessa tulisi projektin testaus onnistua. Saan kuitenkin alla olevan virheen:

> 
> Building Osa06_13.Tehtavat 1.0-SNAPSHOT
> ------------------------------------------------------------------------
> Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-surefire-plugin/2.10/maven-surefire-plugin-2.10.pom
> 
> ------------------------------------------------------------------------
> BUILD FAILURE
> ------------------------------------------------------------------------
> Total time: 0.390s
> Finished at: Fri Feb 21 21:41:51 EET 2020
> Final Memory: 7M/117M
> ------------------------------------------------------------------------
> Plugin org.apache.maven.plugins:maven-surefire-plugin:2.10 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-surefire-plugin:jar:2.10: Could not transfer artifact org.apache.maven.plugins:maven-surefire-plugin:pom:2.10 from/to central (http://repo.maven.apache.org/maven2): Failed to transfer file: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-surefire-plugin/2.10/maven-surefire-plugin-2.10.pom. Return code is: 501 , ReasonPhrase:HTTPS Required. -> [Help 1]
> 
> To see the full stack trace of the errors, re-run Maven with the -e switch.
> Re-run Maven using the -X switch to enable full debug logging.
> 
> For more information about the errors and possible solutions, please read the following articles:
> [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException

Apache Maven, kohta 1:
"You are referring to a non-existing plugin, e.g. by means of a typo in its group id, artifact id or version."

Koitin päivittää pluginit Netbeans -> Tools -> Plugins -> Check for updates, mutta saan seuraavan virheen:

"Unable to connect to the TMC Org/Mooc Edition Updates because of Timeout while opening connection to http://update.testmycode.net/tmc-netbeans_org_mooc/updates.xml".

Ilmeisesti liittyy plugin latausongelmaan, koska ei ole suojattu linkki, mutta kuinka voin vaihtaa sen suojattuun?

**Comment by Aaltoliike** [comment]
Minulla sama ongelma, ensimmäinenkään testi ei mene läpi. Täsmälleen samaa heittää.

**Comment by ConcernedHobbit** [comment]
Ratkaisu on päivittää TMCBeans 1.4.0 ja ladata OpenJDK 11 ensimmäisen osan ohjeiden mukaisesti [tältä sivulta](https://mooc.fi/fi/installation/netbeans).
Suosittelen myös asentamisen jälkeen noudattamaan [näitä ohjeita](https://ohjelmointi-20.mooc.fi/netbeansin-asetusten-poisto) jotta päivitys sujuu vaivattomasti.
