### ISSUE TITLE
Osa 10 - Kysely: Filtteri (väärä vastaus "oikein")

### ISSUE THREAD

**Issue by anstuu** [rage/ohjelmointi-20#56]
Kysely ei hyväksynyt oikeaa vastausta (0), vaan vaatii vastaukseksi 4. 

Liekö copypastevirhe jostakin vanhemmasta kyselyn versiosta, jossa kysytty "Kuinka monta lukua päätyy virran mukana lambda-lausekkeelle "i -> i < 10"?" (nyt siis kysytään "i -> i > 10"?)

<img width="776" alt="Screenshot 2020-03-25 at 16 09 05" src="https://user-images.githubusercontent.com/62655534/77545426-0dec1b00-6eb3-11ea-98aa-a962809a6971.png">

**Comment by laej** [comment]
Huomaa, että tehtävässä ei kysytä ohjelman lopputulosta vaan sitä montako lukua päätyy `.filter(i -> i > 10)` lausekkeelle. Listalla on luvut 0-9, jonka jälkeen siitä suodatetaan kaikki 4 pienemmät eli jäljelle jää 0-3 ja sen jälkeen kukin kerrotaan kahdella. Jäljellä on edelleen neljä lukua 0, 2, 4, 6, jotka siirtyvät seuraavalle filtterille.

**Comment by anstuu** [comment]
Ah, omassa luetunymmärtämisessä näköjään vikaa. Kiitos sinulle!
