### ISSUE TITLE
Osan 2 tehtävässä "Lukujen keskiarvo" ei kerrota, että lukujen pitää olla positiivisia.

### ISSUE THREAD

**Issue by IirisHarkonen** [rage/ohjelmointi-20#88]
Tehtävänannossa ei kerrota, että syötettävien lukujen tulee olla positiivisia, jotta ne otetaan mukaan keskiarvoon (ja tehtävänannon esimerkissä on mukana negatiivinenkin luku).

Kuitenkin tehtävää tarkistaessa tuli tällainen ilmoitus virheestä:
 
FAIL: PositiviistenLukujenKeskiarvoTest test 3
Kun syöte oli:
-1
3
0
, odotettiin tulostusta:
3.0
Tulostusta ei löytynyt.

**Comment by ConcernedHobbit** [comment]
” Kirjoita ohjelma, joka lukee käyttäjältä kokonaislukuja kunnes käyttäjä syöttää luvun 0. Tämän jälkeen ohjelma tulostaa syötteessä esiintyneiden **positiivisten (eli nollaa suurempien lukujen)** keskiarvon.”

**Comment by IirisHarkonen** [comment]
Hei!

Kiitos viestistä! Missä tuo ohje oli?

MOOC Ohjelmointi 2020 -kurssilla (aikatauluttamaton) tehtävässä luki tällainen ohje (ei siis mainintaa lukujen positiivisuudesta):


"Kirjoita ohjelma, joka lukee käyttäjältä lukuja kunnes käyttäjä syöttää luvun 0. Tämän jälkeen ohjelman tulee tulostaa syötettyjen lukujen keskiarvo. Syötteen loppumisesta kertovaa nollaa ei tule ottaa huomioon keskiarvon laskemisessa. Voit olettaa, että käyttäjä syöttää aina vähintään yhden luvun.

Lukujen keskiarvo saadaan jakamalla lukujen summa lukujen lukumäärällä."

Ystävällisin terveisin
Iiris Härkönen
________________________________
Lähettäjä: Eetu Raunio <notifications@github.com>
Lähetetty: keskiviikko 10. kesäkuuta 2020 13.40
Vastaanottaja: rage/ohjelmointi-20 <ohjelmointi-20@noreply.github.com>
Kopio: IirisHarkonen <iiris.harkonen@hotmail.com>; Author <author@noreply.github.com>
Aihe: Re: [rage/ohjelmointi-20] Osan 2 tehtävässä "Lukujen keskiarvo" ei kerrota, että lukujen pitää olla positiivisia. (#88)


” Kirjoita ohjelma, joka lukee käyttäjältä kokonaislukuja kunnes käyttäjä syöttää luvun 0. Tämän jälkeen ohjelma tulostaa syötteessä esiintyneiden positiivisten (eli nollaa suurempien lukujen) keskiarvon.”

**Comment by IirisHarkonen** [comment]
Eikun oho, materiaalissa olikin kaksi tehtävää - kaikkia lukuja koskeva ja positiivisia lukuja koskeva.
Pahoittelut vaivasta!!

Ystävällisin terveisin,
Iiris Härkönen

________________________________
Lähettäjä: Iiris Härkönen <iiris.harkonen@hotmail.com>
Lähetetty: torstai 11. kesäkuuta 2020 9.43
Vastaanottaja: rage/ohjelmointi-20 <reply@reply.github.com>
Aihe: VS: [rage/ohjelmointi-20] Osan 2 tehtävässä "Lukujen keskiarvo" ei kerrota, että lukujen pitää olla positiivisia. (#88)

Hei!

Kiitos viestistä! Missä tuo ohje oli?

MOOC Ohjelmointi 2020 -kurssilla (aikatauluttamaton) tehtävässä luki tällainen ohje (ei siis mainintaa lukujen positiivisuudesta):


"Kirjoita ohjelma, joka lukee käyttäjältä lukuja kunnes käyttäjä syöttää luvun 0. Tämän jälkeen ohjelman tulee tulostaa syötettyjen lukujen keskiarvo. Syötteen loppumisesta kertovaa nollaa ei tule ottaa huomioon keskiarvon laskemisessa. Voit olettaa, että käyttäjä syöttää aina vähintään yhden luvun.

Lukujen keskiarvo saadaan jakamalla lukujen summa lukujen lukumäärällä."

Ystävällisin terveisin
Iiris Härkönen
________________________________
Lähettäjä: Eetu Raunio <notifications@github.com>
Lähetetty: keskiviikko 10. kesäkuuta 2020 13.40
Vastaanottaja: rage/ohjelmointi-20 <ohjelmointi-20@noreply.github.com>
Kopio: IirisHarkonen <iiris.harkonen@hotmail.com>; Author <author@noreply.github.com>
Aihe: Re: [rage/ohjelmointi-20] Osan 2 tehtävässä "Lukujen keskiarvo" ei kerrota, että lukujen pitää olla positiivisia. (#88)


” Kirjoita ohjelma, joka lukee käyttäjältä kokonaislukuja kunnes käyttäjä syöttää luvun 0. Tämän jälkeen ohjelma tulostaa syötteessä esiintyneiden positiivisten (eli nollaa suurempien lukujen) keskiarvon.”
